# Generated by Django 4.0.6 on 2022-07-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='files')),
                ('name', models.CharField(max_length=100)),
                ('predicted_balance', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
